import { createSlice } from '@reduxjs/toolkit';

export const CartSlice = createSlice({
  name: 'cart',
  initialState: {
    items: [], // Initialize items as an empty array
  },
  reducers: {
  
    addItem: (state, action) => {
  const { name, image, cost } = action.payload; // Destructure product details from the action payload
  // Check if the item already exists in the cart by comparing names
  const existingItem = state.items.find(item => item.name === name);
  if (existingItem) {
    // If item already exists in the cart, increase its quantity
    existingItem.quantity++;
  } else {
    // If item does not exist, add it to the cart with quantity 1
    state.items.push({ name, image,cost: cost, quantity: 1 });
  }
},

clearCart: (state) => {
  state.items = [];
},

    
    removeItem: (state, action) => {
      state.items = state.items.filter(item => item.name !== action.payload);

    },
  updateQuantity: (state, action) => {
  const { name, quantity } = action.payload;
  const existingItem = state.items.find(item => item.name === name);
  if (existingItem) {
    if (quantity > 0) {
      existingItem.quantity = quantity;
    } else {
      // Optionally remove item if quantity is zero or less
      state.items = state.items.filter(item => item.name !== name);
    }
  }
}
  },
});

export const { addItem, removeItem, updateQuantity ,clearCart} = CartSlice.actions;

export default CartSlice.reducer;


// Initially, this bag (state) starts with the initialState you define—in your case, items: [] means the cart starts empty.
// As users interact with your app (like adding or removing products), actions are dispatched.

// These actions carry data (payloads) that update the state (the bag), filling it with the current cart items.
// The state always reflects the latest data, and your UI reads from this state to show the current information.
// So, the Redux state is a single source of truth that stores your app’s data, updated predictably via reducers in response to dispatched actions.

// const handleRemove = (item) => {
//   dispatch(removeItem(item));
// };

// const handleIncrement = (item) => {
//   dispatch(updateQuantity({ ...item, quantity: item.quantity + 1 }));
// };
// Here, dispatch sends the action creators (removeItem, updateQuantity) along with the item data (payload) to the Redux store, where the reducers update the state.

// If you don’t see dispatch calls yet in your code, you can add them inside the event handler functions (handleRemove, handleIncrement, etc.) to connect user actions (like clicking a button) with updating the cart state.


// Jo items: [] aapke createSlice ke initialState mein hai, wo Redux store ke andar ka initial data hota hai.

// Hinglish mein samjhaun toh:

// Jab aapka app start hota hai, Redux store banaya jata hai.
// Us store ke andar har slice ka apna ek initial state hota hai — yahan cart slice ka initial state hai { items: [] }.
// Matlab, store ke andar cart naam ka ek hissa hota hai jisme items ek empty array se start hota hai.
// Jab tak user kuch add nahi karta, ye array empty rahega.
// Jaise hi aap addItem ya koi action dispatch karte ho, ye items array update hota hai, aur store ke andar data store ho jata hai.
// Toh simple shabdon mein:
// items: [] wahi initial data hai jo Redux store ke andar cart slice ke liye set kiya gaya hai.

// Slice is where you define the logic for updating the Redux state.
// It includes:
// The initial state (like your empty cart array).
// The reducers, which are functions that specify how the state changes in response to actions.
// The action creators (like addItem, removeItem, updateQuantity) are automatically generated by createSlice based on those reducers.
// When you call these action creators (e.g., dispatch(addItem(payload))), Redux runs the corresponding reducer logic inside the slice to update the state.
// So yes, the slice is like a bundle of logic + actions that controls a part of your app's state.